/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


/**
 *
 * @author LENOVO
 */
public class AgendaFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgendaFrame
     */
    public AgendaFrame() {
        initComponents();     
    }
    
    public String Frq = "X";
    public String Salao = "X";
    public String Tipo = "X";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        txtData = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        rbAvulso = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHora1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHora2 = new javax.swing.JTextField();
        rbMensal = new javax.swing.JRadioButton();
        btnSalvar1 = new javax.swing.JButton();
        rbSemanal = new javax.swing.JRadioButton();
        rbSalao1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rbSalao2 = new javax.swing.JRadioButton();
        rbQuadraFechada = new javax.swing.JRadioButton();
        btnAtualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAgendamentos = new javax.swing.JTextArea();

        jRadioButton1.setText("jRadioButton1");

        setClosable(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        txtData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Data");

        cmbTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Futebol", "Aniversario", "Evento" }));
        cmbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoItemStateChanged(evt);
            }
        });
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Tipo de Evento");

        rbAvulso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbAvulso.setText("AVULSO");
        rbAvulso.setToolTipText("");
        rbAvulso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbAvulsoItemStateChanged(evt);
            }
        });
        rbAvulso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAvulsoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Frequencia");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Horario");

        txtHora1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHora1.setText("00:00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("ás");

        txtHora2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHora2.setText("00:00");

        rbMensal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbMensal.setText("MENSAL");
        rbMensal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbMensalItemStateChanged(evt);
            }
        });

        btnSalvar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalvar1.setText("Salvar");
        btnSalvar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvar1MouseClicked(evt);
            }
        });
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });

        rbSemanal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbSemanal.setText("SEMANAL");
        rbSemanal.setToolTipText("");
        rbSemanal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSemanalItemStateChanged(evt);
            }
        });
        rbSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSemanalActionPerformed(evt);
            }
        });

        rbSalao1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbSalao1.setText("Salão1");
        rbSalao1.setToolTipText("");
        rbSalao1.setEnabled(false);
        rbSalao1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSalao1ItemStateChanged(evt);
            }
        });
        rbSalao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSalao1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Salão");

        rbSalao2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbSalao2.setText("Salão2");
        rbSalao2.setToolTipText("");
        rbSalao2.setEnabled(false);
        rbSalao2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSalao2ItemStateChanged(evt);
            }
        });
        rbSalao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSalao2ActionPerformed(evt);
            }
        });

        rbQuadraFechada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbQuadraFechada.setText("Quadra Fechada");
        rbQuadraFechada.setToolTipText("");
        rbQuadraFechada.setEnabled(false);
        rbQuadraFechada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbQuadraFechadaItemStateChanged(evt);
            }
        });
        rbQuadraFechada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbQuadraFechadaActionPerformed(evt);
            }
        });

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh_1.png"))); // NOI18N
        btnAtualizar.setPreferredSize(new java.awt.Dimension(57, 33));
        btnAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtualizarMouseClicked(evt);
            }
        });
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        txtAgendamentos.setColumns(20);
        txtAgendamentos.setRows(5);
        jScrollPane2.setViewportView(txtAgendamentos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbAvulso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbSemanal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbMensal))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbQuadraFechada)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rbSalao1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rbSalao2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSalvar1))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtHora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtHora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbMensal)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbAvulso)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbSemanal)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbSalao1)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbSalao2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbQuadraFechada)
                            .addComponent(btnSalvar1))
                        .addGap(286, 286, 286))))
        );

        rbAvulso.getAccessibleContext().setAccessibleName("avulsoBotao");
        rbMensal.getAccessibleContext().setAccessibleName("mensalBotao");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void rbAvulsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAvulsoActionPerformed

    }//GEN-LAST:event_rbAvulsoActionPerformed

    private void rbAvulsoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbAvulsoItemStateChanged
        // TODO add your handling code here:
        if (rbAvulso.isSelected()) {
            rbMensal.setSelected(false);
            rbSemanal.setSelected(false);
            Frq = "Avulso";
            
        }
    }//GEN-LAST:event_rbAvulsoItemStateChanged

    private void rbMensalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbMensalItemStateChanged
        // TODO add your handling code here:
        if (rbMensal.isSelected()) {
            rbAvulso.setSelected(false);
            rbSemanal.setSelected(false);
            Frq = "Mensal";
        }
    }//GEN-LAST:event_rbMensalItemStateChanged

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void btnSalvar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvar1MouseClicked
        // TODO add your handling code here:
        if (vazio()) {
            JOptionPane.showMessageDialog(null, "Informe a data!");
        }
        else if (txtHora1.getText().equals("00:00")) {
            JOptionPane.showMessageDialog(null, "Informe a hora de inicio!");
        }
        else if (txtHora2.getText().equals("00:00")) {
            JOptionPane.showMessageDialog(null, "Informe a hora de fim!");
        }
        else if (cmbTipo.getSelectedItem() == " ") {
            JOptionPane.showMessageDialog(null, "Informe o tipo de evento!");
        }
        else if (!rbAvulso.isSelected() && !rbMensal.isSelected()) {
            JOptionPane.showMessageDialog(null, "Informe a frequencia!");
        }
        
        Date data = txtData.getDate();
        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String dataFormatada = formatter.format(data);
        
        
        
        try {
            
            String conteudo = dataFormatada + "|" + cmbTipo.getSelectedItem().toString() + "|" + txtHora1.getText() + " ás " + txtHora2.getText() + "|" 
                + Frq + "|" + Salao + "\n";
        
            FileWriter file = new FileWriter("./src/Agendamentos.txt", true);
  
             file.write(conteudo);
             file.close();
             
             // Imprime confirmacao
            System.out.println("Agendamento Realizado!");
            
        } catch (IOException ex) {
           Logger.getLogger(AgendaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSalvar1MouseClicked

    private void rbSemanalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSemanalItemStateChanged
        // TODO add your handling code here:
        if (rbSemanal.isSelected()) {
            rbAvulso.setSelected(false);
            rbMensal.setSelected(false);
            Frq = "Semanal";
        }
    }//GEN-LAST:event_rbSemanalItemStateChanged

    private void rbSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSemanalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSemanalActionPerformed

    private void cmbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoItemStateChanged
        // TODO add your handling code here:
        
        String item = cmbTipo.getSelectedItem().toString();
        
        if ("Aniversario".equals(item)) {
            rbSalao1.setEnabled(true);
            rbSalao2.setEnabled(true);
            rbQuadraFechada.setEnabled(true);
            Tipo = item;
        }
        else if ("Evento".equals(item)) {
            rbSalao1.setEnabled(true);
            rbSalao2.setEnabled(true);
            rbQuadraFechada.setEnabled(true);
            Tipo = item;
        }
        else{
           rbSalao1.setEnabled(false);
            rbSalao2.setEnabled(false);
            rbQuadraFechada.setEnabled(false); 
            Tipo = "Futebol";
        }

    }//GEN-LAST:event_cmbTipoItemStateChanged

    private void rbSalao1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSalao1ItemStateChanged
        // TODO add your handling code here:
        if (rbSalao1.isSelected()) {
            rbSalao2.setSelected(false);
            rbQuadraFechada.setSelected(false);
            Salao = "Salão1";
        }
    }//GEN-LAST:event_rbSalao1ItemStateChanged

    private void rbSalao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSalao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSalao1ActionPerformed

    private void rbSalao2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSalao2ItemStateChanged
        // TODO add your handling code here:
        if (rbSalao2.isSelected()) {
            rbSalao1.setSelected(false);
            rbQuadraFechada.setSelected(false);
            Salao = "Salão2";
        }
    }//GEN-LAST:event_rbSalao2ItemStateChanged

    private void rbSalao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSalao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSalao2ActionPerformed

    private void rbQuadraFechadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbQuadraFechadaItemStateChanged
        // TODO add your handling code here:
        if (rbQuadraFechada.isSelected()) {
            rbSalao2.setSelected(false);
            rbSalao1.setSelected(false);
            Salao = "Quadra Fechada";
        }
    }//GEN-LAST:event_rbQuadraFechadaItemStateChanged

    private void rbQuadraFechadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbQuadraFechadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbQuadraFechadaActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
       
        File arquivo = new File("./src/Agendamentos.txt" );
        if (arquivo.exists()) {
            String dadosConta[] = new String[4];
          String dados = new String();
            try {
                BufferedReader in = new BufferedReader(new FileReader(arquivo));

                while (in.ready()) {
                    
                    dadosConta = (in.readLine().split(Pattern.quote("|")));
                    dados += dadosConta[0] + " - "+ dadosConta[1]+" - "+ dadosConta[2] + " - " + dadosConta[3]+ " - " + dadosConta[4] + "\n" +
                            "─────────────────────────────────────────────" + "\n"; // linha a linha do txt
                    
                    txtAgendamentos.setText(dados);
                    
                }
                in.close();
            } catch (IOException ex) {
            Logger.getLogger(AgendaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        } else {
            System.out.println("Erro na leitura do arquivo.");
        }   
        
    }//GEN-LAST:event_formComponentShown

    private void btnAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseClicked
        // TODO add your handling code here:
        
        File arquivo = new File("./src/Agendamentos.txt" );
        if (arquivo.exists()) {
            String dadosConta[] = new String[4];
          String dados = new String();
            try {
                BufferedReader in = new BufferedReader(new FileReader(arquivo));

                while (in.ready()) {
                    
                    dadosConta = (in.readLine().split(Pattern.quote("|")));
                    dados += dadosConta[0] + " - "+ dadosConta[1]+" - "+ dadosConta[2] + " - " + dadosConta[3]+ " - " + dadosConta[4] + "\n" +
                            "─────────────────────────────────────────────" + "\n"; // linha a linha do txt
                    
                    txtAgendamentos.setText(dados);
                    
                }
                in.close();
            } catch (IOException ex) {
            Logger.getLogger(AgendaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        } else {
            System.out.println("Erro na leitura do arquivo.");
        } 
        
    }//GEN-LAST:event_btnAtualizarMouseClicked

   public boolean vazio() 
{        
    return txtData.getDate() == null;    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbAvulso;
    private javax.swing.JRadioButton rbMensal;
    private javax.swing.JRadioButton rbQuadraFechada;
    private javax.swing.JRadioButton rbSalao1;
    private javax.swing.JRadioButton rbSalao2;
    private javax.swing.JRadioButton rbSemanal;
    private javax.swing.JTextArea txtAgendamentos;
    private com.toedter.calendar.JDateChooser txtData;
    public javax.swing.JTextField txtHora1;
    private javax.swing.JTextField txtHora2;
    // End of variables declaration//GEN-END:variables
}
